### ISSUE TITLE
Documentation doesn't mention need for python-rsa package

### ISSUE THREAD

**Issue by gene1wood** [mdipierro/evote#19]
Out of the box evote depends on the python module `rsa`. Without it you get the traceback below. Probably a good idea to add this to the quick start instructions. Under [RHEL or RHEL derivatives](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux_derivatives#List_of_Red_Hat_Enterprise_Linux_derivatives) this involves running `sudo yum install python-rsa` or Debian/Ubuntu `sudo apt-get install python-rsa`

```
Traceback (most recent call last):
  File "/home/gene/web2py/gluon/restricted.py", line 224, in restricted
    exec ccode in environment
  File "/home/gene/web2py/applications/evote/controllers/default.py", line 1, in <module>
    from ballot import ballot2form, form2ballot, blank_ballot, \
  File "/home/gene/web2py/gluon/custom_import.py", line 92, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/evote/modules/ballot.py", line 3, in <module>
    import rsa
  File "/home/gene/web2py/gluon/custom_import.py", line 86, in custom_importer
    raise ImportError, 'Cannot import module %s' % str(e)
ImportError: Cannot import module 'applications.evote.modules.rsa'
```

**Comment by erwanlr** [comment]
Other modules are also needed, such as git and asn1 ;)
