### ISSUE TITLE
Internal Server Error after fresh install.

### ISSUE THREAD

**Issue by atdtn** [mdipierro/evote#37]
Hello.

After quick start instructions,
visiting localhost:3000/evote/default/index causes an internal server error. 

Here are more details:

Version
web2py™   Version 2.21.1-stable+timestamp.2020.11.28.04.10.44
Python  Python 3.8.7: /Users/username/tmp/web2py/venv/bin/python (prefix: /Users/username/tmp/web2py/venv/bin/..)

Traceback (most recent call last):
  File "/Users/username/tmp/web2py/gluon/main.py", line 439, in wsgibase
    serve_controller(request, response, session)
  File "/Users/username/tmp/web2py/gluon/main.py", line 175, in serve_controller
    page = run_controller_in(request.controller, request.function, environment)
  File "/Users/username/tmp/web2py/gluon/compileapp.py", line 655, in run_controller_in
    ccode = getcfs(layer, filename, lambda: compile2(code, filename))
  File "/Users/username/tmp/web2py/gluon/cfs.py", line 50, in getcfs
    data = filter()
  File "/Users/username/tmp/web2py/gluon/compileapp.py", line 655, in <lambda>
    ccode = getcfs(layer, filename, lambda: compile2(code, filename))
  File "/Users/username/tmp/web2py/gluon/restricted.py", line 205, in compile2
    return compile(code, layer, 'exec')
  File "/Users/username/tmp/web2py/applications/evote/controllers/default.py", line 231
    print "ballot id:",ballot.id, "key:",key, "results[key]:",results[key], "vote:",vote
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("ballot id:",ballot.id, "key:",key, "results[key]:",results[key], "vote:",vote)?

**Comment by mdipierro** [comment]
Evote was written for python 2. Would be nice to convert it to 3. I doubt i
will have the time anytime soon

**Comment by mcnamara-charles** [comment]
Hi there, I have coded a 3.9 version of mdipierro's evote system @ https://github.com/mcnamara-charles/evote-3.9
